### ISSUE TITLE
Make the height of the bottom sheet adjustable

### ISSUE THREAD

**Issue by f-person** [caseyryan/flutter_cupernino_bottom_sheet#1]
I am not sure how well a different height value will work with the current way of doing things (screenshotting), but there are cases when you don't want your bottom sheets to take the whole screen height. It would be nice to either infer the size of the bottom sheet from its children or make it possible to set a fixed height.

**Comment by caseyryan** [comment]
Hi! It's not the case for this kind of UI. This one is always supposed to be full screen
